"""Generate the endpoint table in docs/API_SPEC.md from the application's own routes and role guards.

The roles column is read from each route's `require(...)` dependency, so it cannot disagree with what the server enforces.
tests/api/test_api_doc_in_sync.py fails when the committed table is stale (`python scripts/gen_docs.py` rewrites it).
"""

from fastapi import FastAPI
from fastapi.routing import APIRoute

from .deps import authenticate

API_PREFIX = "/api/v1"
BEGIN, END = "<!-- BEGIN GENERATED ENDPOINTS -->", "<!-- END GENERATED ENDPOINTS -->"
CRUD_PURPOSE = {"list_": "List / filter / search (paged)", "get_": "One row by id", "create_": "Create",
                "update_": "Partial update", "delete_": "Delete (refused while dependants exist)"}


def _routes(routes, prefix: str = ""):
    """Yield (full path, APIRoute) for every route, descending into included routers (all mounted under /api/v1)."""
    for route in routes:
        if isinstance(route, APIRoute):
            yield prefix + route.path, route
        elif (inner := getattr(route, "original_router", None)) is not None:
            yield from _routes(inner.routes, API_PREFIX)


def _roles(dependant) -> str:
    """'public', 'any signed-in user' or the role list, found anywhere in the route's dependency tree."""
    stack, signed_in = [dependant], False
    while stack:
        dep = stack.pop()
        if (roles := getattr(dep.call, "roles", None)) is not None:
            return ", ".join(roles) if roles else "any signed-in user"
        signed_in |= dep.call is authenticate
        stack.extend(dep.dependencies)
    return "any signed-in user" if signed_in else "public"


def _purpose(route: APIRoute) -> str:
    paragraph = " ".join((route.endpoint.__doc__ or "").strip().split("\n\n")[0].split())
    first_sentence = paragraph.split(". ")[0].rstrip(".") + "." if paragraph else ""
    return first_sentence or CRUD_PURPOSE.get(route.name) or route.name.replace("_", " ").capitalize()


def _tag(route: APIRoute) -> str:
    return route.tags[0] if route.tags else "system"


def endpoint_table(app: FastAPI) -> str:
    rows = sorted(((path, method, route) for path, route in _routes(app.routes) if route.include_in_schema
                   for method in route.methods), key=lambda r: (_tag(r[2]), r[0], r[1]))
    out = [BEGIN, "", f"{len(rows)} operations. Generated by `python scripts/gen_docs.py`; do not edit by hand."]
    tag = None
    for path, method, route in rows:
        if _tag(route) != tag:
            tag = _tag(route)
            out += ["", f"### {tag}", "", "| Method | Path | Who may call it | Purpose |", "|---|---|---|---|"]
        out.append(f"| `{method}` | `{path}` | {_roles(route.dependant)} | {_purpose(route).replace('|', '/')} |")
    return "\n".join(out + ["", END])


def splice(document: str, table: str) -> str:
    """Replace the generated block inside `document` with `table`."""
    head, rest = document.split(BEGIN, 1)
    return head + table + rest.split(END, 1)[1]
