"""Generate docs/SCHEMA_REFERENCE.md from the migrated database's own catalogue.

Hand-written schema documentation drifts; this cannot. tests/db/test_docs_in_sync.py regenerates it from a fresh migration
and fails when the committed file differs, telling the contributor to run `python scripts/gen_schema_doc.py`.
"""

import psycopg

HEADER = """# Schema reference (generated)

> **Generated** by `python scripts/gen_schema_doc.py` from the migrated database catalogue. **Do not edit by hand**; a test
> fails when this file is out of date. The reasoning behind the design is in [DATABASE_DESIGN.md](DATABASE_DESIGN.md) and the
> diagrams are in [ER_DIAGRAM.md](ER_DIAGRAM.md).

Schema revision: `{revision}` · PostgreSQL {version} · {count} application tables.

How to read it: *a foreign key with no `ON DELETE` clause is `NO ACTION`: deleting the referenced row is refused while
dependants exist.* Check, unique and exclusion constraints are shown exactly as PostgreSQL stores them. Row-level security
policies and triggers are listed per table.

"""

CONTYPE = {"p": "Primary key", "u": "Unique", "f": "Foreign key", "c": "Check", "x": "Exclusion"}


def generate(conn: psycopg.Connection) -> str:
    cur = conn.cursor(row_factory=psycopg.rows.tuple_row)
    revision = cur.execute("SELECT version_num FROM alembic_version").fetchone()[0]
    version = cur.execute("SHOW server_version").fetchone()[0].split()[0].split(".")[0]    # major only: minor releases must not break the sync test
    tables = cur.execute("""
        SELECT c.oid, c.relname, obj_description(c.oid, 'pg_class'), c.relrowsecurity
        FROM pg_class c WHERE c.relnamespace = 'public'::regnamespace AND c.relkind = 'r' AND c.relname <> 'alembic_version'
        ORDER BY c.relname""").fetchall()

    out = [HEADER.format(revision=revision, version=version, count=len(tables))]
    out.append("| Table | Purpose |\n|---|---|")
    out += [f"| [`{name}`](#{name}) | {(comment or '').replace('|', '/')} |" for _, name, comment, _ in tables]
    out.append("")

    for oid, name, comment, rls in tables:
        out += [f"## {name}", "", comment or "", ""]
        out += ["| Column | Type | Null? | Default |", "|---|---|---|---|"]
        for col, typ, notnull, default, identity in cur.execute("""
            SELECT a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull, pg_get_expr(d.adbin, d.adrelid), a.attidentity
            FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
            WHERE a.attrelid = %s AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum""", (oid,)):
            shown = {"a": "generated always as identity", "d": "generated by default as identity"}.get(identity) or default or ""
            out.append(f"| `{col}` | {typ} | {'NOT NULL' if notnull else 'nullable'} | {('`' + shown + '`') if shown else ''} |")
        out.append("")

        constraints = cur.execute("""
            SELECT contype, conname, pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid = %s
            ORDER BY array_position(ARRAY['p','u','f','c','x']::text[], contype::text), conname""", (oid,)).fetchall()
        if constraints:
            out += ["**Constraints**", "", "| Kind | Name | Definition |", "|---|---|---|"]
            out += [f"| {CONTYPE[t]} | `{n}` | `{d.replace('|', chr(92) + '|')}` |" for t, n, d in constraints]
            out.append("")

        indexes = cur.execute("""
            SELECT c.relname, pg_get_indexdef(i.indexrelid) FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid
            WHERE i.indrelid = %s AND NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conindid = i.indexrelid)
            ORDER BY c.relname""", (oid,)).fetchall()
        if indexes:
            out += ["**Indexes** (beyond those that back the constraints above)", ""]
            out += [f"- `{n}`: `{d.split(' USING ', 1)[1] if ' USING ' in d else d}`" for n, d in indexes]
            out.append("")

        triggers = cur.execute("""
            SELECT tgname, pg_get_triggerdef(oid) FROM pg_trigger WHERE tgrelid = %s AND NOT tgisinternal ORDER BY tgname""", (oid,)).fetchall()
        if triggers:
            out += ["**Triggers**", ""]
            out += [f"- `{n}`: `{d.split(' ON ', 1)[0].replace('CREATE TRIGGER ' + n + ' ', '')} ... {d.split(' EXECUTE FUNCTION ')[-1]}`" for n, d in triggers]
            out.append("")

        policies = cur.execute("""
            SELECT policyname, cmd, qual, with_check FROM pg_policies WHERE schemaname = 'public' AND tablename = %s ORDER BY cmd, policyname""", (name,)).fetchall()
        if rls:
            out += ["**Row-level security** is ENABLED (the table owner and superusers bypass it; the application role does not)", ""]
            out += [f"- `{p}` for {c}: " + (f"USING `{q}`" if q else "") + (f" WITH CHECK `{w}`" if w else "") for p, c, q, w in policies]
            out.append("")
    return "\n".join(out).rstrip() + "\n"
